# Generated by Django 3.2.8 on 2021-10-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='other_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Социальная сеть'),
        ),
    ]
