# Generated by Django 3.2.8 on 2021-10-20 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_auto_20211020_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='num',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='количество слоёв'),
        ),
    ]
