# Generated by Django 3.2.8 on 2021-10-20 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0004_alter_layer_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cake.component', verbose_name='компонент'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='num',
            field=models.PositiveSmallIntegerField(verbose_name='количество слоёв'),
        ),
    ]
