# Generated by Django 3.2.8 on 2021-10-20 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0007_alter_order_topping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='topping',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cake.topping', verbose_name='топпинг'),
        ),
    ]
