# Generated by Django 3.2.8 on 2021-10-20 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0010_auto_20211020_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='topping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cake.topping', verbose_name='топпинг'),
        ),
    ]
