# Generated by Django 3.2.8 on 2021-10-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0011_alter_order_topping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='topping',
        ),
        migrations.AddField(
            model_name='order',
            name='topping',
            field=models.ManyToManyField(blank=True, to='cake.Topping', verbose_name='топпинг'),
        ),
    ]
