# Generated by Django 3.2.8 on 2021-10-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0014_auto_20211021_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='active',
            field=models.BooleanField(default=False, verbose_name='активен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Заявка обрабатывается'), ('PREPARING_CAKE', 'Готовим ваш торт'), ('ON_THE_WAY', 'Торт в пути'), ('DELIVERED', 'Торт у вас'), ('CANCELLED', 'Отменён')], db_index=True, default='NEW', max_length=20, verbose_name='Статус'),
        ),
    ]
