# Generated by Django 3.2.8 on 2021-10-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0016_order_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='num',
            field=models.CharField(max_length=15, unique=True, verbose_name='промокод'),
        ),
    ]
