# Generated by Django 3.2.8 on 2021-10-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0018_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promocode',
            field=models.CharField(max_length=15, unique=True, verbose_name='промокод'),
        ),
        migrations.DeleteModel(
            name='Promo',
        ),
    ]
