# Generated by Django 3.2.8 on 2021-10-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0020_alter_order_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='адрес'),
        ),
    ]
