# Generated by Django 3.2.8 on 2021-10-22 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0021_alter_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='промокод')),
                ('discont_percent', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Скидка %')),
                ('active', models.BooleanField(default=False, verbose_name='активен')),
            ],
            options={
                'verbose_name': ('Промокод',),
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='promocode',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='промокод'),
        ),
    ]
