# Generated by Django 3.2.8 on 2021-10-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0023_auto_20211025_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='параметр')),
                ('param_descr', models.CharField(max_length=30, verbose_name='описание параметра')),
                ('param_value', models.CharField(max_length=30, verbose_name='значение параметра')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
            },
        ),
        migrations.AlterModelOptions(
            name='promo',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
